# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: "npm" # See documentation for possible values
      directory: "/frontend" # Location of package manifests
      schedule:
          interval: "daily"
      labels:
          - "Frontend Dependency"
      open-pull-requests-limit: 0

      # Enable version updates for Backend
    - package-ecosystem: "npm"
      directory: "/backend"
      schedule:
          interval: "daily"
      labels:
          - "Backend Dependency"
      open-pull-requests-limit: 0
