import type { NextPage } from "next"
import Head from "next/head"
import Checkout from "../components/CheckOut"

const CheckOut: NextPage = () => {
  return (
    <>
      <Head>
        <title>Check Out</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" mx-auto">
        <div className="mt-5">
          <div className=" mt-5 flex flex-col gap-y-2">
            <Checkout />
          </div>
        </div>
      </main>
    </>
  )
}

export default CheckOut