import type { NextPage } from "next"
import Head from "next/head"
import Feedback from "../components/Feedback"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" mx-auto">
        <div className="mt-5">
          {/* <h3 className="font-bold text-lg tracking-wide px-5 py-5 border-b text-center">
            Papermaker!!!
          </h3> */}
          <div className=" mt-5 flex flex-col gap-y-2">
            <Feedback />
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
