import type { NextPage } from "next"
import Head from "next/head"
import PapermakerRegisterForm from "../components/PapermakerRegisterForm"

const Register: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" mx-auto">
          <div className="flex flex-col gap-y-2">
            <PapermakerRegisterForm />
          </div>
      </main>
    </>
  )
}

export default Register
