import type { NextPage } from "next"
import Head from "next/head"
import PapermakerRegisterForm from "../components/PapermakerRegisterForm"

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Become a papermaker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto">
        <div>
          <PapermakerRegisterForm />
        </div>
      </main>
    </>
  )
}

export default Register
